pipeline {
    agent any

    parameters {
        string(name: 'env', defaultValue: 'dev', description: 'Deployment environment (dev/sit/uat)')
    }

    environment {
        ANSIBLE_CONFIG = "${WORKSPACE}/ansible.cfg"
        ANSIBLE_HOST_KEY_CHECKING = 'False'
    }

    stages {

        stage('Initial Cleanup') {
            steps {
                dir("${WORKSPACE}") {
                    deleteDir()
                }
            }
        }

        stage('Checkout SCM') {
            steps {
                git branch: 'main',
                    credentialsId: 'github',
                    url: 'https://github.com/Ngumonelson123/ansible-configuration-mgt.git'
            }
        }

        stage('Prepare Ansible Environment') {
            steps {
                sh 'echo "Deploying to ${env} environment"'
            }
        }

        stage('Run Ansible Playbook') {
            steps {
                ansiblePlaybook(
                    playbook: 'playbooks/site.yml',
                    inventory: "inventory/${env}",
                    credentialsId: 'ansible-key',
                    colorized: true
                )
            }
        }

        stage('Clean Workspace after build') {
            steps {
                cleanWs(cleanWhenAborted: true, cleanWhenFailure: true, cleanWhenNotBuilt: true, cleanWhenUnstable: true, deleteDirs: true)
            }
        }

    }
}
