---
- name: Configure common settings on all hosts
  import_playbook: ../static-assignments/common.yml

- name: Configure database server
  import_playbook: db.yml

- name: Configure webservers
  import_playbook: webservers.yml

- name: Configure Nginx reverse proxy
  import_playbook: nginx.yml
